version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-cbo
    restart: always
    environment:
      POSTGRES_DB: cbo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cbo
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: flask-api
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cbo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./cbo.csv:/app/cbo.csv

volumes:
  pg_data:
