version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cbo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Porta do PostgreSQL no host
    volumes:
      - pg_data:/var/lib/postgresql/data  # Volume para persistência dos dados
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - "6380:6379"  # Porta do Redis no host para evitar conflito com a porta 6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  api:
    image: ggabrielfferreira19/minha-api-flask
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"  # Porta da API no host
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cbo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - default

volumes:
  pg_data: {}  # Volume para persistência de dados do PostgreSQL

networks:
  default:
    driver: overlay  # Rede overlay para comunicação entre contêineres no Swarm
