version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cbo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default  # Adiciona a rede à lista

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default  # Adiciona a rede à lista

  api:
    image: ggabrielfferreira19/minha-api-flask
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cbo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - default  # Adiciona a rede à lista

volumes:
  pg_data: {}

networks:
  default:
    driver: overlay  # Configuração da rede overlay
